### ISSUE TITLE
footnote option is not handling \multsidenote when fnpct is loaded

### ISSUE THREAD

**Issue by cgnieder** [cgnieder/snotez#1]
**[Original report](https://bitbucket.org/cgnieder/snotez/issue/1) by Frank Mittelbach (Bitbucket: [FMittelbach](https://bitbucket.org/FMittelbach), ).**

----------------------------------------

Example showing the problem :
```
#!latex

\documentclass{article}

\setlength\marginparwidth{80pt}

\setlength\textheight{10\baselineskip}
\setlength\textwidth{200pt}

\usepackage{fnpct,snotez}
\setsidenotes{footnote,text-format=\tiny,note-mark-format=(#1)}

\begin{document}

\ldots out of
straw\sidenote*{not to be confused with hay},
sticks\sidenote{or lumber according to some
  sources} and bricks\multsidenote{probably fired
  clay bricks;Several in a row?}.

\ldots out of
straw\footnote*{not to be confused with hay},
sticks\footnote{or lumber according to some
  sources} and bricks\multfootnote{probably fired
  clay bricks;Several in a row?}.

\end{document}
```

Result:

`\multsidenote` ends up in the margin but `\multfootnote` at the bottom.

**Comment by FrankMittelbach** [comment]
Any chance of seeing this fixed?

**Comment by cgnieder** [comment]
Oh, thanks for the reminder! Yes, I'll fix this tonight.

**Comment by FrankMittelbach** [comment]
I forgot to mention that (not surprisingly) `\multfootnote` will in that case also generate footnotes not sidenotes; not checked if your fix repairs that too (probably does).

**Comment by cgnieder** [comment]
The output was now as it should be:

![image](https://user-images.githubusercontent.com/2248538/102711357-522d1000-42b9-11eb-9f6a-a7f1046ebfed.png)
